### ISSUE TITLE
Create build system?

### ISSUE THREAD

**Issue by shawndwells** [usnistgov/oscal-tools#18]
Creating a profile. such as FedRAMP or another agency (e.g. DHS 4300A) requires 5,000+ lines of XML. 

Propose a shorthand build system be created. Something akin to how SCAP Security Guide decomposed XCCDF and OVAL rules into singular files that are merged together into specification-correct SCAP.

Currently to cumbersome to create profiles with existing workflow. 

Does NIST envision authoritative content (e.g. profiles, like FedRAMP) to be created in this repo, or should an open source content project be created (aka fold this into the ComplianceAsCode efforts)?

**Comment by wendellpiez** [comment]
Noting that OSCAL content now lives in another repo as well: https://github.com/usnistgov/oscal-content.

**Comment by david-waltermire-nist** [comment]
Since this issue was created, we have added YAML support for defining OSCAL profiles. The [SP 800-53 rev5 LOW baseline in YAML](https://github.com/usnistgov/oscal-content/blob/main/nist.gov/SP800-53/rev5/yaml/NIST_SP-800-53_rev5_LOW-baseline_profile.yaml) is only 190 lines. The CI/CD in the oscal-content repo will auto generate XML and JSON representations. Furthermore, tooling like the Java-based [oscal-cli](https://github.com/usnistgov/oscal-cli) is being developed to provide commodity tooling to support translation between XML, JSON, and YAML, and to support profile resolution.

Given all this work happening in other repos, I believe it is ok to close this issue.

**Comment by wendellpiez** [comment]
Closing because we can always reopen.

**Comment by shawndwells** [comment]
+1

This is several years old now. Time to move on :)

**Comment by aj-stein-nist** [comment]
Shawn is here? Can I ask questions about OpenControl? ;-)

**Comment by shawndwells** [comment]
> Shawn is here? Can I ask questions about OpenControl? ;-)

Hah! I lurk :) OpenControl was a great first step back in the day!
